version: "3.8"

services:
  db:
    image: postgres:16.3-alpine3.19
    restart: always
    shm_size: 128mb
    container_name: postgres_test
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test

    ports:
      - 8001:5432

    volumes:
      - data:/var/lib/postgresql_test/data

volumes:
  data:

networks:
  connect_to_nestjs:
    external: true

